[package]
name = "g-flite"
version = "0.1.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]
edition = "2018"

[dependencies]
hound = { git="https://github.com/kubkon/hound" }
docopt = "1.1"
serde = { version="1.0", features=["derive"] }
serde_json = "1.0"
indicatif = "0.11"
console = ">=0.7.1, <1.0.0"

[[bin]]
name = "g_flite"
path = "src/main.rs"
