[package]
name = "g-flite"
version = "0.1.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]
edition = "2018"

[dependencies]
hound = { git="https://github.com/kubkon/hound" }
docopt = "1.1.0"
serde = { version="1.0.91", features=["derive"] }
serde_json = "1.0.39"
serde_yaml = "0.8.9"
indicatif = "0.11.0"
console = ">=0.7.1, <1.0.0"
actix = "0.8.1"
log = "0.4.6"
env_logger = "0.6.1"
failure="0.1.5"
futures = "0.1.26"
prettytable-rs = "0.8.0"
lazy_static = "1.3.0"
golem-rpc-api = { git="https://github.com/golemfactory/golem-client" }
actix-wamp = { git="https://github.com/golemfactory/golem-client" }
wamp-derive = { git="https://github.com/golemfactory/golem-client" }

[[bin]]
name = "g_flite"
path = "src/main.rs"
